export const GET_CATEOGORIES_REQUESTED = "categories.GET_CATEOGORIES_REQUESTED";
export const GET_CATEOGORIES_SUCCEEDED = "categories.GET_CATEOGORIES_SUCCEEDED";
export const GET_CATEOGORIES_FAILED = "categories.GET_CATEOGORIES_FAILED";